# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-20 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.BooleanField(default=False),
        ),
    ]
